// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBreQ5YDvjkrRSRqiCWrNjVl5MDE38CKYQ',
    appId: '1:520106767791:web:3899a9e29d3e50cfd5eb5a',
    messagingSenderId: '520106767791',
    projectId: 'uni-wien-emperors',
    authDomain: 'uni-wien-emperors.firebaseapp.com',
    storageBucket: 'uni-wien-emperors.firebasestorage.app',
    measurementId: 'G-XSNK5MD71S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8LNKcfyy3zXhq8-YtLrO1uNykGkEgYI',
    appId: '1:520106767791:android:3692d4f3f1d3ed38d5eb5a',
    messagingSenderId: '520106767791',
    projectId: 'uni-wien-emperors',
    storageBucket: 'uni-wien-emperors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyTufhxBOooBM7WX2Kv2IvA__utv7a-og',
    appId: '1:520106767791:ios:a7a38f4f6a3cb84dd5eb5a',
    messagingSenderId: '520106767791',
    projectId: 'uni-wien-emperors',
    storageBucket: 'uni-wien-emperors.firebasestorage.app',
    iosBundleId: 'felpower.software.emperors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpK_35LEWzhRKt9ssHWTZ-cDRZU4lNloM',
    appId: '1:156609466347:web:174cf3dd9256917cd193ae',
    messagingSenderId: '156609466347',
    projectId: 'klinikkorneuburg',
    authDomain: 'klinikkorneuburg.firebaseapp.com',
    storageBucket: 'klinikkorneuburg.appspot.com',
    measurementId: 'G-V3PXKMQGM8',
  );
}